In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
x = np.array([2,3,4,5,5,7,8])
print(x)
print('total elements=>',x.size)
print('dimension wise element=> ',x.shape)
print('dimension count', x.ndim)

[2 3 4 5 5 7 8]
total elements=> 7
dimension wise element=>  (7,)
dimension count 1


In [7]:
y = np.array([[2,3,4],[3,2,1]])
print(y)
print('total elements=>',y.size)
print('dimension wise element=> ',y.shape)
print('dimension count', y.ndim)

[[2 3 4]
 [3 2 1]]
total elements=> 6
dimension wise element=>  (2, 3)
dimension count 2


In [9]:
z = np.array([[2,3,4],[3,2,1],[8,9,5]])
print(z)
print('total elements=>',z.size)
print('dimension wise element=> ',z.shape)
print('dimension count', z.ndim)

[[2 3 4]
 [3 2 1]
 [8 9 5]]
total elements=> 9
dimension wise element=>  (3, 3)
dimension count 2


In [24]:
x= [1,2,3,4,5]
z = np.array([[x,x,x],[x,x,x],[x,x,x]])
print('total elements=>',z.shape)
print(z)

total elements=> (3, 3, 5)
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [29]:
x= [1,2,3,4,5]
z = np.array([[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x]])
print('dimension wise element=> ',z.shape)
print('dimension count', z.ndim)
print(z)

dimension wise element=>  (11, 3, 5)
dimension count 3
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [36]:
d = np.arange(-10,11,.5)
d.shape

(42,)

In [39]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [40]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [45]:
a = np.linspace(1, 1000, 11)
a

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [48]:
d = np.random.randint(1,6,(10,10))

In [49]:
print(d)

[[2 2 3 5 5 5 3 5 4 2]
 [5 1 2 1 3 4 1 4 3 4]
 [4 1 3 2 4 3 2 2 5 3]
 [5 2 1 4 5 1 4 4 1 5]
 [1 4 1 4 2 5 3 5 2 1]
 [1 1 4 2 1 4 4 2 4 4]
 [4 1 4 4 3 2 2 2 2 4]
 [4 5 5 4 5 1 2 3 3 1]
 [2 2 5 5 1 5 2 4 2 5]
 [3 1 4 2 3 5 3 5 4 1]]


In [50]:
d[0]

array([2, 2, 3, 5, 5, 5, 3, 5, 4, 2])

In [51]:
d[0][0]

2

In [53]:
d[3][4]

5

In [54]:
d[:,0] #all rows of column idx 0

array([2, 5, 4, 5, 1, 1, 4, 4, 2, 3])

In [55]:
d[:5,2]

array([3, 2, 3, 1, 1])

In [57]:
d[:5, :5]

array([[2, 2, 3, 5, 5],
       [5, 1, 2, 1, 3],
       [4, 1, 3, 2, 4],
       [5, 2, 1, 4, 5],
       [1, 4, 1, 4, 2]])

In [58]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3,3))
print(x, '\n',y)

[[9 7 1]
 [1 3 6]
 [9 5 9]] 
 [[1 5 7]
 [7 8 4]
 [1 3 4]]


In [61]:
x+y


array([[10, 12,  8],
       [ 8, 11, 10],
       [10,  8, 13]])

In [62]:
x-y

array([[ 8,  2, -6],
       [-6, -5,  2],
       [ 8,  2,  5]])

In [63]:
x*y

array([[ 9, 35,  7],
       [ 7, 24, 24],
       [ 9, 15, 36]])

In [64]:
x/y

array([[9.        , 1.4       , 0.14285714],
       [0.14285714, 0.375     , 1.5       ],
       [9.        , 1.66666667, 2.25      ]])

In [65]:
x + 10


array([[19, 17, 11],
       [11, 13, 16],
       [19, 15, 19]])

In [66]:
x - 10

array([[-1, -3, -9],
       [-9, -7, -4],
       [-1, -5, -1]])

In [67]:
x*10

array([[90, 70, 10],
       [10, 30, 60],
       [90, 50, 90]])

In [68]:
np.dot(x,y)

array([[ 59, 104,  95],
       [ 28,  47,  43],
       [ 53, 112, 119]])

In [69]:
np.matmul(x,y)

array([[ 59, 104,  95],
       [ 28,  47,  43],
       [ 53, 112, 119]])

In [70]:
np.multiply(x,y)

array([[ 9, 35,  7],
       [ 7, 24, 24],
       [ 9, 15, 36]])

In [71]:
x*y

array([[ 9, 35,  7],
       [ 7, 24, 24],
       [ 9, 15, 36]])

In [72]:
np.cross(x,y)

array([[ 44, -62,  38],
       [-36,  38, -13],
       [ -7, -27,  22]])

In [73]:
np.hstack([x,y])

array([[9, 7, 1, 1, 5, 7],
       [1, 3, 6, 7, 8, 4],
       [9, 5, 9, 1, 3, 4]])

In [74]:
np.vstack([x,y])

array([[9, 7, 1],
       [1, 3, 6],
       [9, 5, 9],
       [1, 5, 7],
       [7, 8, 4],
       [1, 3, 4]])

In [75]:
np.append(x,[1,2,3])

array([9, 7, 1, 1, 3, 6, 9, 5, 9, 1, 2, 3])

In [76]:
np.append(x,y,axis=0)

array([[9, 7, 1],
       [1, 3, 6],
       [9, 5, 9],
       [1, 5, 7],
       [7, 8, 4],
       [1, 3, 4]])

In [78]:
x.max(axis=0)

array([9, 7, 9])

In [79]:
x.max()

9

In [84]:
x.min(axis=1)

array([1, 1, 5])

In [86]:
x.flatten()

array([9, 7, 1, 1, 3, 6, 9, 5, 9])

In [88]:
d [d > 3]  #boolean filter

array([5, 5, 5, 5, 4, 5, 4, 4, 4, 4, 4, 5, 5, 4, 5, 4, 4, 5, 4, 4, 5, 5,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 4, 5, 5, 5, 5, 4, 5, 4, 5, 5,
       4])

In [89]:
d[d==1] # d=give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [90]:
d> 3

array([[False, False, False,  True,  True,  True, False,  True,  True,
        False],
       [ True, False, False, False, False,  True, False,  True, False,
         True],
       [ True, False, False, False,  True, False, False, False,  True,
        False],
       [ True, False, False,  True,  True, False,  True,  True, False,
         True],
       [False,  True, False,  True, False,  True, False,  True, False,
        False],
       [False, False,  True, False, False,  True,  True, False,  True,
         True],
       [ True, False,  True,  True, False, False, False, False, False,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [False, False,  True,  True, False,  True, False,  True, False,
         True],
       [False, False,  True, False, False,  True, False,  True,  True,
        False]])