In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
x = np.array([2,3,4,5,5,7,8])
print(x)
print('total elements=>',x.size)
print('dimension wise element=> ',x.shape)
print('dimension count', x.ndim)

[2 3 4 5 5 7 8]
total elements=> 7
dimension wise element=>  (7,)
dimension count 1


In [7]:
y = np.array([[2,3,4],[3,2,1]])
print(y)
print('total elements=>',y.size)
print('dimension wise element=> ',y.shape)
print('dimension count', y.ndim)

[[2 3 4]
 [3 2 1]]
total elements=> 6
dimension wise element=>  (2, 3)
dimension count 2


In [9]:
z = np.array([[2,3,4],[3,2,1],[8,9,5]])
print(z)
print('total elements=>',z.size)
print('dimension wise element=> ',z.shape)
print('dimension count', z.ndim)

[[2 3 4]
 [3 2 1]
 [8 9 5]]
total elements=> 9
dimension wise element=>  (3, 3)
dimension count 2


In [ ]:
x= [1,2,3,4,5,6,7,8]
z = np.array([x,x,x],[x,x,x],[])