In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
x = np.array([2,3,4,5,5,7,8])
print(x)
print('total elements=>',x.size)
print('dimension wise element=> ',x.shape)
print('dimension count', x.ndim)

[2 3 4 5 5 7 8]
total elements=> 7
dimension wise element=>  (7,)
dimension count 1


In [4]:
y = np.array([[2,3,4],[3,2,1]])
print(y)
print('total elements=>',y.size)
print('dimension wise element=> ',y.shape)
print('dimension count', y.ndim)

[[2 3 4]
 [3 2 1]]
total elements=> 6
dimension wise element=>  (2, 3)
dimension count 2


In [5]:
z = np.array([[2,3,4],[3,2,1],[8,9,5]])
print(z)
print('total elements=>',z.size)
print('dimension wise element=> ',z.shape)
print('dimension count', z.ndim)

[[2 3 4]
 [3 2 1]
 [8 9 5]]
total elements=> 9
dimension wise element=>  (3, 3)
dimension count 2


In [6]:
x= [1,2,3,4,5]
z = np.array([[x,x,x],[x,x,x],[x,x,x]])
print('total elements=>',z.shape)
print(z)

total elements=> (3, 3, 5)
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [7]:
x= [1,2,3,4,5]
z = np.array([[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x],[x,x,x]])
print('dimension wise element=> ',z.shape)
print('dimension count', z.ndim)
print(z)

dimension wise element=>  (11, 3, 5)
dimension count 3
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [8]:
d = np.arange(-10,11,.5)
d.shape

(42,)

In [9]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [10]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [11]:
a = np.linspace(1, 1000, 11)
a

array([   1. ,  100.9,  200.8,  300.7,  400.6,  500.5,  600.4,  700.3,
        800.2,  900.1, 1000. ])

In [12]:
d = np.random.randint(1,6,(10,10))

In [13]:
print(d)

[[2 1 3 2 4 4 4 3 2 5]
 [1 4 4 2 2 4 5 4 3 4]
 [4 3 5 3 2 5 1 2 3 3]
 [1 5 4 5 1 3 2 3 5 3]
 [5 4 1 2 3 1 5 3 5 5]
 [2 3 2 5 1 5 3 1 1 3]
 [2 5 4 1 4 1 4 3 5 3]
 [2 5 1 2 1 1 5 3 2 3]
 [4 4 4 4 1 4 2 2 3 5]
 [3 5 2 1 5 5 4 3 5 1]]


In [14]:
d[0]

array([2, 1, 3, 2, 4, 4, 4, 3, 2, 5])

In [15]:
d[0][0]

2

In [16]:
d[3][4]

1

In [17]:
d[:,0] #all rows of column idx 0

array([2, 1, 4, 1, 5, 2, 2, 2, 4, 3])

In [18]:
d[:5,2]

array([3, 4, 5, 4, 1])

In [19]:
d[:5, :5]

array([[2, 1, 3, 2, 4],
       [1, 4, 4, 2, 2],
       [4, 3, 5, 3, 2],
       [1, 5, 4, 5, 1],
       [5, 4, 1, 2, 3]])

In [20]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1, 10, (3,3))
print(x, '\n',y)

[[7 4 5]
 [7 7 9]
 [3 6 4]] 
 [[2 2 1]
 [4 5 7]
 [4 5 8]]


In [21]:
x+y


array([[ 9,  6,  6],
       [11, 12, 16],
       [ 7, 11, 12]])

In [22]:
x-y

array([[ 5,  2,  4],
       [ 3,  2,  2],
       [-1,  1, -4]])

In [23]:
x*y

array([[14,  8,  5],
       [28, 35, 63],
       [12, 30, 32]])

In [24]:
x/y

array([[3.5       , 2.        , 5.        ],
       [1.75      , 1.4       , 1.28571429],
       [0.75      , 1.2       , 0.5       ]])

In [25]:
x + 10


array([[17, 14, 15],
       [17, 17, 19],
       [13, 16, 14]])

In [26]:
x - 10

array([[-3, -6, -5],
       [-3, -3, -1],
       [-7, -4, -6]])

In [27]:
x*10

array([[70, 40, 50],
       [70, 70, 90],
       [30, 60, 40]])

In [28]:
np.dot(x,y)

array([[ 50,  59,  75],
       [ 78,  94, 128],
       [ 46,  56,  77]])

In [29]:
np.matmul(x,y)

array([[ 50,  59,  75],
       [ 78,  94, 128],
       [ 46,  56,  77]])

In [30]:
np.multiply(x,y)

array([[14,  8,  5],
       [28, 35, 63],
       [12, 30, 32]])

In [31]:
x*y

array([[14,  8,  5],
       [28, 35, 63],
       [12, 30, 32]])

In [32]:
np.cross(x,y)

array([[ -6,   3,   6],
       [  4, -13,   7],
       [ 28,  -8,  -9]])

In [33]:
np.hstack([x,y])

array([[7, 4, 5, 2, 2, 1],
       [7, 7, 9, 4, 5, 7],
       [3, 6, 4, 4, 5, 8]])

In [34]:
np.vstack([x,y])

array([[7, 4, 5],
       [7, 7, 9],
       [3, 6, 4],
       [2, 2, 1],
       [4, 5, 7],
       [4, 5, 8]])

In [35]:
np.append(x,[1,2,3])

array([7, 4, 5, 7, 7, 9, 3, 6, 4, 1, 2, 3])

In [36]:
np.append(x,y,axis=0)

array([[7, 4, 5],
       [7, 7, 9],
       [3, 6, 4],
       [2, 2, 1],
       [4, 5, 7],
       [4, 5, 8]])

In [37]:
x.max(axis=0)

array([7, 7, 9])

In [38]:
x.max()

9

In [39]:
x.min(axis=1)

array([4, 7, 3])

In [40]:
x.flatten()

array([7, 4, 5, 7, 7, 9, 3, 6, 4])

In [41]:
d [d > 3]  #boolean filter

array([4, 4, 4, 5, 4, 4, 4, 5, 4, 4, 4, 5, 5, 5, 4, 5, 5, 5, 4, 5, 5, 5,
       5, 5, 5, 4, 4, 4, 5, 5, 5, 4, 4, 4, 4, 4, 5, 5, 5, 5, 4, 5])

In [42]:
d[d==1] # d=give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
d> 3

array([[False, False, False, False,  True,  True,  True, False, False,
         True],
       [False,  True,  True, False, False,  True,  True,  True, False,
         True],
       [ True, False,  True, False, False,  True, False, False, False,
        False],
       [False,  True,  True,  True, False, False, False, False,  True,
        False],
       [ True,  True, False, False, False, False,  True, False,  True,
         True],
       [False, False, False,  True, False,  True, False, False, False,
        False],
       [False,  True,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False, False, False, False,  True, False, False,
        False],
       [ True,  True,  True,  True, False,  True, False, False, False,
         True],
       [False,  True, False, False,  True,  True,  True, False,  True,
        False]])